CREATE TABLE IF NOT EXISTS auto_warn_settings (
    group_id BIGINT NOT NULL REFERENCES groups(chat_id) ON DELETE CASCADE PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
